package models

// Order model
type Order struct {
	ID           uint      `json:"id"` // ID is not required because it is generated by the database
	CustomerID   string    `json:"customer_id" binding:"required"`
	CanBeShipped bool      `json:"can_be_shipped"`
	IsPayed      bool      `json:"is_payed"`
	Products     []Product `json:"products" binding:"required"`
}

type Product struct {
	ID          uint     `json:"id" binding:"required"`
	Name        string   `json:"name" binding:"required"`
	Description string   `json:"description" binding:"required"`
	Price       uint     `json:"price" binding:"required"`
	Color       string   `json:"color"`
	Types       []string `json:"types"`
}
